const OWNER_ADDRESS_UPDATE = "OWNER_ADDRESS_UPDATE";
const USER_ADDRESS_UPDATE = "USER_ADDRESS_UPDATE";
const EVENT_LIST_ADD = "EVENT_LIST_ADD";
const IS_ADMIN_UPDATE = "IS_ADMIN_UPDATE";

export { OWNER_ADDRESS_UPDATE, USER_ADDRESS_UPDATE, EVENT_LIST_ADD,IS_ADMIN_UPDATE}


